---
title: "Timmy Chicago Master Analysis"
author: "Timmy Miller"
date: "10/15/2020"
output: html_document

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width = 12, fig.height = 12)
library(tidyverse)
library(tidycensus)
library(reshape2)
library(ggcorrplot)
```



```{r, include=FALSE}
chicago_master<-read_csv("../Data/chicago_master_for_service_model.csv")
```



```{r, include=FALSE}
###correlation heatmap derived from http://www.sthda.com/english/wiki/ggplot2-quick-correlation-matrix-heatmap-r-software-and-data-visualization

cormat<- round(cor(chicago_master), 2)
head(cormat)

```


```{r, include=FALSE}
get_upper_tri <- function(cormat){
    cormat[lower.tri(cormat)]<- NA
    return(cormat)
  }
```

```{r, include=FALSE}
upper_tri <- get_upper_tri(cormat)
melted_cormat <- melt(upper_tri, na.rm = TRUE)
```



```{r, include=FALSE}
reorder_cormat <- function(cormat){
# Use correlation between variables as distance
dd <- as.dist((1-cormat)/2)
hc <- hclust(dd)
cormat <-cormat[hc$order, hc$order]
}
```

```{r, include=FALSE}
# Reorder the correlation matrix
cormat <- reorder_cormat(cormat)
upper_tri <- get_upper_tri(cormat)
# Melt the correlation matrix
melted_cormat <- melt(upper_tri, na.rm = TRUE)
# Create a ggheatmap
ggheatmap1 <- ggplot(melted_cormat, aes(Var2, Var1, fill = value))+
 geom_tile(color = "white")+
 scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
   midpoint = 0, limit = c(-1,1), space = "Lab", 
    name="Pearson\nCorrelation") +
  theme_minimal()+ # minimal theme
 theme(axis.text.x = element_text(angle = 90, vjust = 1, 
    size = 5, hjust = 1))+theme(axis.text.y = element_text( vjust = 1, 
    size = 5, hjust = 1))+
 coord_fixed()
```

```{r, include=FALSE}
ggheatmap1 + 
geom_text(aes(Var2, Var1, label = value), color = "black", size = 1.6) +
theme(
  axis.title.x = element_blank(),
  axis.title.y = element_blank(),
  panel.grid.major = element_blank(),
  panel.border = element_blank(),
  panel.background = element_blank(),
  axis.ticks = element_blank(),
  legend.justification = c(1, 0),
  legend.position = c(0.6, 0.7),
  legend.direction = "horizontal")+
  guides(fill = guide_colorbar(barwidth = 7, barheight = 1,
                title.position = "top", title.hjust = 0.5))
###show in new window to see this with optimal sizing, need to figure out how to knit this better
```





```{r, echo=FALSE}
#or make using ggcorrplot; this example shows only coefficients with significant p-values
p.mat <- cor_pmat(chicago_master)
ggcorrplot(cormat, p.mat = p.mat, hc.order = TRUE,
    type = "lower", insig = "blank", lab=TRUE, lab_size=2.5)+theme(axis.text.x = element_text(angle = 45, vjust = 1, 
    size = 12, hjust = 1))+theme(axis.text.y = element_text( vjust = 1, 
    size = 12, hjust = 1))
```

