---
title: "Chicago Master For Service Model Data Dictionary"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Chicago Master data frame dictionary

What follows is an explanation for all of the variables in `chicago_master_for_service_model.csv`. All populations are estimated, which in turns means proportions are estimated.

- **GEOID:** ZIP code
- **zip_pop:** Population
- **zip_pop_hisp:** Population of Hispanic or Latino
- **zip_pop_work_eligible:** Population that is eligible for work
- **prop_over_18:** Proportion of population over 18 years
- **prop_citizen:** Proportion of population that are citizens (by any means)
- **prop_female_over_18:** Proportion of population that are female and over 18 years old
- **prop_female_citizen:** Proportion of population that are female and citizens (by any means)
- **prop_over_18_citizen:** Proportion of population that are over 18 years and are citizens (by any means)
- **prop_female_over_18_citizen:** Proportion of population that are female, over 18 years old, and are citizens (by any means)
- **prop_female_hisp:** Proportion of the Hispanic or Latino population that are female
- **prop_prop_18_to_34_hisp:** Proportion of the Hispanic or Latino population that are between 18 and 34 years old
- **prop_female_18_to_34_hisp:** Proportion of the Hispanic or Latino population that are female and between 18 and 34 years old
- **prop_19_to_34:** Proportion of the population that are between 19 and 34 years old
- **prop_with_HI:** Proportion of the population that has some type of health insurance
- **prop_female_19_to_34:** Proportion of the population that is female and between 19 and 34 years old
- **prop_female_with_HI:** Proportion of the population that is female and has some type of health insurance
- **prop_19_to_34_with_HI:** Proportion of the population that is between 19 and 34 years old and has some type of health insurance
- **prop_female_19_to_34_with_HI:** Proportion of the population that is female, between 19 and 34 years old, and has some type of health insurance
- **prop_not_His:** Proportion of the population that is not Hispanic or Latino
- **prop_White:** Proportion of the population that is white
- **prop_not_His_White:** Proportion of the population that is not Hispanic or Latino and is white
- **prop_male_work_eligible:** Proportion of the work-eligible population that is male
- **prop_service:** Proportion of the work-eligible population that is defined as a service worker
- **prop_male_work_eligible_service:** Proportion of the work-eligible population that is male and is defined as a service worker
- **prop_female:** Proportion of the population that is female
- **prop_18_to_34:** Proportion of the population that is between 18 and 34 years old
- **prop_female_18_to_34:** Proportion of the population that is female and between 18 and 34 years old
- **prop_one_policy:** Proportion of the population that has a single health insurance policy
- **prop_employer:** Proportion of the population that has employer-based health insurance only
- **prop_medicaid:** Proportion of the population that has Medicaid or means-tested public coverage only
- **prop_19_to_34_one_policy:** Proportion of the population that is between 19 and 34 years old and has a single health insurance policy
- **prop_19_to_34_no_HI:** Proportion of the population that is between 19 and 34 years old and has no health insurance coverage
- **prop_19_to_34_employer:** Proportion of the population that is between 19 and 34 years old and has employer-based health insurance only
- **prop_19_to_34_medicaid:** Proportion of the population that is between 19 and 34 years old and has Medicaid or means-tested public coverage only

